import { FormEvent, useEffect, useState } from "react";
import { listarAuditoria, RegistroAuditoria } from "../api/auditoria";
import { ApiError } from "../api/client";
import Boton from "../components/Boton";
import EmptyState from "../components/EmptyState";
import PageHeader from "../components/PageHeader";
import SectionHeader from "../components/SectionHeader";
import { useAuth } from "../context/AuthContext";

const ACCIONES: Record<string, string> = { crear_usuario: "Creó una cuenta", dar_de_baja_usuario: "Dio de baja una cuenta", reactivar_usuario: "Reactivó una cuenta", resetear_password: "Restableció una contraseña", crear_trabajador: "Registró un trabajador", editar_trabajador: "Actualizó un trabajador", aplicar_sueldo_masivo_seleccion: "Aplicó una actualización masiva", aplicar_sueldo_masivo_por_categoria: "Aplicó una actualización por categoría", crear_nomina: "Generó una nómina", corregir_nomina: "Corrigió una nómina", crear_terminal: "Registró una terminal", editar_terminal: "Actualizó una terminal" };
const etiquetaAccion = (accion: string) => ACCIONES[accion] ?? accion.replaceAll("_", " ");
export default function AuditoriaPage() {
  const { sesion } = useAuth(); const token = sesion!.token;
  const [registros, setRegistros] = useState<RegistroAuditoria[]>([]); const [total, setTotal] = useState(0); const [pagina, setPagina] = useState(1); const [actor, setActor] = useState(""); const [consulta, setConsulta] = useState(""); const [seleccionado, setSeleccionado] = useState<RegistroAuditoria | null>(null); const [cargando, setCargando] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { listarAuditoria(token, { actor: consulta, pagina, limite: 25 }).then((r) => { setRegistros(r.registros); setTotal(r.total); setError(null); }).catch((e) => setError(e instanceof ApiError ? e.message : "No se pudo consultar la auditoría.")).finally(() => setCargando(false)); }, [token, consulta, pagina]);
  function buscar(e: FormEvent) { e.preventDefault(); setPagina(1); setConsulta(actor.trim()); }
  return <div style={{ padding: "26px 30px 36px" }}><PageHeader titulo="Auditoría" descripcion="Consulta acciones relevantes realizadas dentro del sistema." metadata="Historial de actividad" />
    <div className="tarjeta-admin" style={{ marginTop: 16, overflow: "hidden" }}><SectionHeader titulo="Actividad registrada" descripcion={`${total} acciones disponibles · más recientes primero`} /><form onSubmit={buscar} className="filters-bar" style={{ padding: "0 20px 16px" }}><input aria-label="Buscar por usuario" value={actor} onChange={(e) => setActor(e.target.value)} placeholder="Buscar por usuario actor" /><Boton tamano="pequeno" type="submit">Buscar</Boton></form>
      {error ? <div role="alert" className="module-message error">{error}</div> : cargando ? <div className="module-message">Cargando historial…</div> : registros.length === 0 ? <EmptyState titulo="No hay acciones registradas" descripcion="La actividad administrativa auditada aparecerá aquí." /> : <div className="table-scroll"><table className="tabla-premium"><thead><tr><th>Fecha</th><th>Usuario</th><th>Acción</th><th>Módulo</th><th>Detalle</th></tr></thead><tbody>{registros.map((r) => <tr key={r.id}><td>{new Date(r.fecha).toLocaleString("es-MX")}</td><td><strong>{r.actorUsername}</strong></td><td>{etiquetaAccion(r.accion)}</td><td>{r.entidad}</td><td><Boton tamano="pequeno" variante="outline" onClick={() => setSeleccionado(r)}>Ver detalle</Boton></td></tr>)}</tbody></table></div>}
      <div className="pagination"><Boton tamano="pequeno" variante="outline" disabled={pagina === 1} onClick={() => setPagina((p) => p - 1)}>Anterior</Boton><span>Página {pagina}</span><Boton tamano="pequeno" variante="outline" disabled={pagina * 25 >= total} onClick={() => setPagina((p) => p + 1)}>Siguiente</Boton></div></div>
    {seleccionado && <div className="modal-backdrop" onClick={() => setSeleccionado(null)}><div role="dialog" aria-modal="true" aria-label="Detalle de auditoría" className="modal-panel audit-modal" onClick={(e) => e.stopPropagation()}><h3>Detalle de auditoría</h3><dl><dt>Fecha</dt><dd>{new Date(seleccionado.fecha).toLocaleString("es-MX")}</dd><dt>Usuario</dt><dd>{seleccionado.actorUsername}</dd><dt>Acción</dt><dd>{etiquetaAccion(seleccionado.accion)}</dd><dt>Entidad</dt><dd>{seleccionado.entidad}</dd></dl>{seleccionado.detalle.length ? <ul>{seleccionado.detalle.map((d) => <li key={d}>{d}</li>)}</ul> : <p>Sin información adicional visible.</p>}<Boton onClick={() => setSeleccionado(null)}>Cerrar</Boton></div></div>}
  </div>;
}
